[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
serde = "1.0.152"
strum = { version = "0.24.1", features = ["derive"] }
stylist = { version = "0.11.0", features = ["yew", "yew_use_style", "yew_integration"] }
yew = { version = "0.20.0", features = ["csr"] }
