[build]
public_url = "/"
dist = "../static"

[watch]
watch = [".", "../common"]

[[proxy]]
backend = "http://localhost:3000/api"

[[proxy]]
backend = "ws://localhost:3000/ws/game"
ws = true

[[proxy]]
backend = "ws://localhost:3000/ws/canvas"
ws = true

[[proxy]]
backend = "ws://localhost:3000/ws/chat"
ws = true
