[workspace]
resolver = "2"
members = ["frontend", "backend", "common"]
default-members = ["backend"]

[workspace.dependencies]
common = { path = "common" }
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
strum = "0.26"
