[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/shuttle.rs"

[dependencies]
anyhow = "1.0"
axum = { version = "0.6", features = ["ws"] }
axum-sessions = "0.4"
common = { path = "../common" }
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
shuttle-service = { version = "0.8.0", features = ["web-axum"] }
surrealdb = { version = "1.0.0-beta.8", default-features = true, features = ["parallel", "kv-mem", "scripting"] } # sudo apt install libclang-dev clang
sync_wrapper = "0.1"
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.3", features = ["fs"] }
